language: python
python:
  - "3.6"

cache:
    directories:
    - bin #cache .weights files
    
# command to install dependencies
install: 
    - pip install -r $TRAVIS_BUILD_DIR/test/requirements-testing.txt
    - pip install $TRAVIS_BUILD_DIR

# command to run tests
script: pytest