language: python
python:
  - "3.6"

cache:
    directories:
    - bin #cache .weights files
    
# command to install dependencies
install: 
    - "pip install -r ./test/test-requirements.txt"
    - "pip install -r ."

# command to run tests
script: pytest