dist: trusty
sudo: false

language: python
python:
  - "3.6"

cache:
    directories:
    - bin #cache .weights files
    
# command to install dependencies
install: 
    - pip install -r test/requirements-testing.txt
    - pip install .

# command to run tests
script: coverage run -m pytest -x

#Upload code coverage statistics
after_success:
  codecov